spring.datasource.url=jdbc:postgresql://localhost:5432/lojinha
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

security.jwt.expiration=30
security.jwt.key=IHdhYmJhIGxhYmJhIGR1YiBkdWIgd2FiYmEgbGFiYmEgZHViIGR1YiB3YWJiYSBsYWJiYSBkdWIgZHViIHdhYmJhIGxhYmJhIGR1YiBkdWIg

#spring.application.name=Lojinha
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect